# Generated by Django 4.2.4 on 2023-08-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=30)),
                ('Language', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=10)),
            ],
        ),
    ]
